apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-subscriber-reply
  namespace: exp
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-subscriber
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
      namespace: exp