apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reply-trigger
  namespace: exp
spec:
  broker: default
  filter:
    attributes:
      type: parse.order.finish
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-producer-service
    uri: /reply  