apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-producer
  namespace: exp
  labels:
    app: event-producer
spec:
  selector:
    matchLabels:
      app: event-producer
  template:
    metadata:
      labels:
        app: event-producer
    spec:
      containers:
        - name: event-producer
          image: gcr.io/clearbanc-api-dev/knative-source:v5
          imagePullPolicy: Always

---

# A deployment creates a set of pods and you need a centralized way of communicating with those pods
# This is where a service comes to play, it is responsible for enabling network access to a set of pods.
apiVersion: v1
kind: Service
metadata:
  name: event-producer-service
  namespace: exp
  labels:
    app: event-producer-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  type: NodePort
  # When the node receives a request it will
  # "select pods with the label 'app' set to 'api'"
  # and forward the request to one of them
  selector:
    app: event-producer
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
  - port: 80
    # The api container accepts http requests at 8080, this where requests are targeted
    # defined in the api container by 'containerPort' and named 'port-http'
    targetPort: 8080
    protocol: TCP
