apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-producer-subscriber
  namespace: exp
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: event-producer
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
      namespace: exp