apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-trigger
  namespace: exp
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-subscriber