apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: "exp"
spec:
  secretTargetRef:
  - parameter: host
    name: keda-rabbitmq-secret
    key: host